import React from "react";
import {
  Calendar,
  Gauge,
  Twitter,
  Image,
  Languages,
  Link as LinkIcon,
  Facebook,
  FileText,
  Music,
  Instagram,
  Smartphone,
  Youtube,
  Clapperboard,
  Crown,
  Download,
  PlayCircle,
  Share2,
  Zap,
  Monitor,
  Globe,
  Scissors,
  Camera,
  Headphones,
  DownloadCloud,
  Film,
  Play,
  Calculator,
  Clock,
  Gift,
  Star,
  Trophy,
  Users,
  Volume2,
  ArrowRightLeft,
  RefreshCw,
  File,
  Heart,
  Video,
} from "lucide-react";

// Mapping of icon keys to rendered icon elements (standard size)
export const iconMap: Record<string, JSX.Element> = {
  calendar: <Calendar className="w-6 h-6" />,
  gauge: <Gauge className="w-6 h-6" />,
  twitter: <Twitter className="w-6 h-6" />,
  image: <Image className="w-6 h-6" />,
  languages: <Languages className="w-6 h-6" />,
  link: <LinkIcon className="w-6 h-6" />,
  facebook: <Facebook className="w-6 h-6" />,
  filetext: <FileText className="w-6 h-6" />,
  music: <Music className="w-6 h-6" />,
  instagram: <Instagram className="w-6 h-6" />,
  smartphone: <Smartphone className="w-6 h-6" />,
  youtube: <Youtube className="w-6 h-6" />,
  clapperboard: <Clapperboard className="w-6 h-6" />,
  crown: <Crown className="w-6 h-6" />,
  download: <Download className="w-6 h-6" />,
  playcircle: <PlayCircle className="w-6 h-6" />,
  share2: <Share2 className="w-6 h-6" />,
  zap: <Zap className="w-6 h-6" />,
  monitor: <Monitor className="w-6 h-6" />,
  globe: <Globe className="w-6 h-6" />,
  scissors: <Scissors className="w-6 h-6" />,
  camera: <Camera className="w-6 h-6" />,
  headphones: <Headphones className="w-6 h-6" />,
  downloadcloud: <DownloadCloud className="w-6 h-6" />,
  film: <Film className="w-6 h-6" />,
  play: <Play className="w-6 h-6" />,
  calculator: <Calculator className="w-6 h-6" />,
  clock: <Clock className="w-6 h-6" />,
  gift: <Gift className="w-6 h-6" />,
  star: <Star className="w-6 h-6" />,
  trophy: <Trophy className="w-6 h-6" />,
  users: <Users className="w-6 h-6" />,
  volume2: <Volume2 className="w-6 h-6" />,
  arrowrightleft: <ArrowRightLeft className="w-6 h-6" />,
  refreshcw: <RefreshCw className="w-6 h-6" />,
  file: <File className="w-6 h-6" />,
  heart: <Heart className="w-6 h-6" />,
  video: <Video className="w-6 h-6" />,
};

// Export a list of all available icon keys so admin can pick any icon for any tool
export const allIconKeys = Object.keys(iconMap);

// Per-tool icon options: provide the full icon set for each tool so admins can choose any icon.
export const perToolIconOptions: Record<string, string[]> = {
  "age-calculator": allIconKeys,
  "background-remover": allIconKeys,
  "facebook-video-downloader": allIconKeys,
  "youtube-video-downloader": allIconKeys,
  "twitter-video-downloader": allIconKeys,
  "tiktok-video-downloader": allIconKeys,
  "instagram-video-downloader": allIconKeys,
  "youtube-to-mp3": allIconKeys,
  "url-shortener": allIconKeys,
  "internet-speed-test": allIconKeys,
  "pdf-to-word-converter": allIconKeys,
  "language-translator": allIconKeys,
};

// Generic fallback options to show when a slug isn't mapped (all icons)
export const genericIconOptions = allIconKeys;

export default iconMap;
