import { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "hi" | "zh" | "es" | "pt" | "bn" | "ru" | "ar" | "ja" | "ko" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    "nav.tools": "Tools",
    "nav.pricing": "Pricing",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "hero.title": "All-in-One Online Tools Platform",
    "hero.subtitle": "Download videos, convert files, check internet speed, and access 12+ powerful tools. Fast, secure, and free to use.",
    "hero.explore": "Explore Tools",
    "hero.pricing": "View Pricing",
    "tools.popular": "Popular Tools",
    "tools.subtitle": "Choose from our collection of powerful online tools",
    "tools.all": "All Tools",
    "tools.video": "Video Tools",
    "tools.converter": "Converters",
    "tools.utility": "Utilities",
    "tools.free": "Free",
    "tools.premium": "Premium",
    "pricing.title": "Choose Your Plan",
    "pricing.subtitle": "Unlock premium features and remove limits",
    "pricing.free": "Free",
    "pricing.monthly": "Monthly",
    "pricing.yearly": "Yearly",
    "pricing.current": "Current Plan",
    "pricing.getStarted": "Get Started",
    "pricing.save": "Save 17%",
    "footer.tagline": "Your one-stop solution for all online tools and utilities.",
    "footer.about": "About Us",
    "footer.contact": "Contact Us",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.support": "Support",
    "settings.title": "Settings",
    "settings.account": "Account Settings",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.notifications": "Notifications"
  },
  hi: {
    "nav.tools": "उपकरण",
    "nav.pricing": "मूल्य निर्धारण",
    "nav.about": "के बारे में",
    "nav.contact": "संपर्क",
    "nav.login": "लॉग इन करें",
    "nav.signup": "साइन अप करें",
    "hero.title": "सभी-इन-वन ऑनलाइन टूल्स प्लेटफॉर्म",
    "hero.subtitle": "वीडियो डाउनलोड करें, फाइलें कन्वर्ट करें, इंटरनेट स्पीड चेक करें, और 12+ शक्तिशाली टूल्स का उपयोग करें।",
    "hero.explore": "टूल्स देखें",
    "hero.pricing": "मूल्य देखें",
    "tools.popular": "लोकप्रिय उपकरण",
    "tools.subtitle": "हमारे शक्तिशाली ऑनलाइन टूल्स के संग्रह से चुनें",
    "tools.all": "सभी टूल्स",
    "tools.video": "वीडियो टूल्स",
    "tools.converter": "कन्वर्टर",
    "tools.utility": "उपयोगिताएं",
    "tools.free": "मुफ्त",
    "tools.premium": "प्रीमियम",
    "pricing.title": "अपना प्लान चुनें",
    "pricing.subtitle": "प्रीमियम सुविधाओं को अनलॉक करें और सीमाएं हटाएं",
    "pricing.free": "मुफ्त",
    "pricing.monthly": "मासिक",
    "pricing.yearly": "वार्षिक",
    "pricing.current": "वर्तमान प्लान",
    "pricing.getStarted": "शुरू करें",
    "pricing.save": "17% बचाएं",
    "footer.tagline": "सभी ऑनलाइन टूल्स और उपयोगिताओं के लिए आपका एक-स्टॉप समाधान।",
    "footer.about": "हमारे बारे में",
    "footer.contact": "संपर्क करें",
    "footer.privacy": "गोपनीयता नीति",
    "footer.terms": "सेवा की शर्तें",
    "footer.support": "सहायता",
    "settings.title": "सेटिंग्स",
    "settings.account": "खाता सेटिंग्स",
    "settings.language": "भाषा",
    "settings.theme": "थीम",
    "settings.notifications": "अधिसूचनाएं"
  },
  zh: {
    "nav.tools": "工具",
    "nav.pricing": "价格",
    "nav.about": "关于",
    "nav.contact": "联系",
    "nav.login": "登录",
    "nav.signup": "注册",
    "hero.title": "一体化在线工具平台",
    "hero.subtitle": "下载视频、转换文件、检查网速，访问12+强大工具。快速、安全、免费使用。",
    "hero.explore": "探索工具",
    "hero.pricing": "查看价格",
    "tools.popular": "热门工具",
    "tools.subtitle": "从我们强大的在线工具集合中选择",
    "tools.all": "所有工具",
    "tools.video": "视频工具",
    "tools.converter": "转换器",
    "tools.utility": "实用工具",
    "tools.free": "免费",
    "tools.premium": "高级",
    "pricing.title": "选择您的计划",
    "pricing.subtitle": "解锁高级功能并移除限制",
    "pricing.free": "免费",
    "pricing.monthly": "月度",
    "pricing.yearly": "年度",
    "pricing.current": "当前计划",
    "pricing.getStarted": "开始使用",
    "pricing.save": "节省 17%",
    "footer.tagline": "您的一站式在线工具和实用程序解决方案。",
    "footer.about": "关于我们",
    "footer.contact": "联系我们",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
    "footer.support": "支持",
    "settings.title": "设置",
    "settings.account": "账户设置",
    "settings.language": "语言",
    "settings.theme": "主题",
    "settings.notifications": "通知"
  },
  es: {
    "nav.tools": "Herramientas",
    "nav.pricing": "Precios",
    "nav.about": "Acerca de",
    "nav.contact": "Contacto",
    "nav.login": "Iniciar sesión",
    "nav.signup": "Registrarse",
    "hero.title": "Plataforma de Herramientas Online Todo-en-Uno",
    "hero.subtitle": "Descarga videos, convierte archivos, verifica velocidad de internet y accede a 12+ herramientas poderosas.",
    "hero.explore": "Explorar Herramientas",
    "hero.pricing": "Ver Precios",
    "tools.popular": "Herramientas Populares",
    "tools.subtitle": "Elige de nuestra colección de herramientas online poderosas",
    "tools.all": "Todas las Herramientas",
    "tools.video": "Herramientas de Video",
    "tools.converter": "Convertidores",
    "tools.utility": "Utilidades",
    "tools.free": "Gratis",
    "tools.premium": "Premium",
    "pricing.title": "Elige Tu Plan",
    "pricing.subtitle": "Desbloquea características premium y elimina límites",
    "pricing.free": "Gratis",
    "pricing.monthly": "Mensual",
    "pricing.yearly": "Anual",
    "pricing.current": "Plan Actual",
    "pricing.getStarted": "Comenzar",
    "pricing.save": "Ahorra 17%",
    "footer.tagline": "Tu solución integral para todas las herramientas y utilidades online.",
    "footer.about": "Acerca de Nosotros",
    "footer.contact": "Contáctanos",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Servicio",
    "footer.support": "Soporte",
    "settings.title": "Configuración",
    "settings.account": "Configuración de Cuenta",
    "settings.language": "Idioma",
    "settings.theme": "Tema",
    "settings.notifications": "Notificaciones"
  },
  pt: {
    "nav.tools": "Ferramentas",
    "nav.pricing": "Preços",
    "nav.about": "Sobre",
    "nav.contact": "Contato",
    "nav.login": "Entrar",
    "nav.signup": "Cadastrar",
    "hero.title": "Plataforma de Ferramentas Online Tudo-em-Um",
    "hero.subtitle": "Baixe vídeos, converta arquivos, verifique velocidade da internet e acesse 12+ ferramentas poderosas.",
    "hero.explore": "Explorar Ferramentas",
    "hero.pricing": "Ver Preços",
    "tools.popular": "Ferramentas Populares",
    "tools.subtitle": "Escolha da nossa coleção de ferramentas online poderosas",
    "tools.all": "Todas as Ferramentas",
    "tools.video": "Ferramentas de Vídeo",
    "tools.converter": "Conversores",
    "tools.utility": "Utilitários",
    "tools.free": "Grátis",
    "tools.premium": "Premium",
    "pricing.title": "Escolha Seu Plano",
    "pricing.subtitle": "Desbloqueie recursos premium e remova limites",
    "pricing.free": "Grátis",
    "pricing.monthly": "Mensal",
    "pricing.yearly": "Anual",
    "pricing.current": "Plano Atual",
    "pricing.getStarted": "Começar",
    "pricing.save": "Economize 17%",
    "footer.tagline": "Sua solução completa para todas as ferramentas e utilitários online.",
    "footer.about": "Sobre Nós",
    "footer.contact": "Entre em Contato",
    "footer.privacy": "Política de Privacidade",
    "footer.terms": "Termos de Serviço",
    "footer.support": "Suporte",
    "settings.title": "Configurações",
    "settings.account": "Configurações da Conta",
    "settings.language": "Idioma",
    "settings.theme": "Tema",
    "settings.notifications": "Notificações"
  },
  bn: {
    "nav.tools": "টুলস",
    "nav.pricing": "মূল্য",
    "nav.about": "সম্পর্কে",
    "nav.contact": "যোগাযোগ",
    "nav.login": "লগইন",
    "nav.signup": "সাইন আপ",
    "hero.title": "সব-এক-এ অনলাইন টুলস প্ল্যাটফর্ম",
    "hero.subtitle": "ভিডিও ডাউনলোড করুন, ফাইল রূপান্তর করুন, ইন্টারনেট স্পিড চেক করুন এবং ১২+ শক্তিশালী টুলস ব্যবহার করুন।",
    "hero.explore": "টুলস দেখুন",
    "hero.pricing": "মূল্য দেখুন",
    "tools.popular": "জনপ্রিয় টুলস",
    "tools.subtitle": "আমাদের শক্তিশালী অনলাইন টুলসের সংগ্রহ থেকে বেছে নিন",
    "tools.all": "সব টুলস",
    "tools.video": "ভিডিও টুলস",
    "tools.converter": "রূপান্তরকারী",
    "tools.utility": "ইউটিলিটি",
    "tools.free": "বিনামূল্যে",
    "tools.premium": "প্রিমিয়াম",
    "pricing.title": "আপনার প্ল্যান বেছে নিন",
    "pricing.subtitle": "প্রিমিয়াম বৈশিষ্ট্য আনলক করুন এবং সীমা সরান",
    "pricing.free": "বিনামূল্যে",
    "pricing.monthly": "মাসিক",
    "pricing.yearly": "বার্ষিক",
    "pricing.current": "বর্তমান প্ল্যান",
    "pricing.getStarted": "শুরু করুন",
    "pricing.save": "১৭% সাশ্রয় করুন",
    "footer.tagline": "সব অনলাইন টুলস এবং ইউটিলিটিজের জন্য আপনার এক-স্টপ সমাধান।",
    "footer.about": "আমাদের সম্পর্কে",
    "footer.contact": "যোগাযোগ করুন",
    "footer.privacy": "গোপনীয়তা নীতি",
    "footer.terms": "সেবার শর্তাবলী",
    "footer.support": "সহায়তা",
    "settings.title": "সেটিংস",
    "settings.account": "অ্যাকাউন্ট সেটিংস",
    "settings.language": "ভাষা",
    "settings.theme": "থিম",
    "settings.notifications": "বিজ্ঞপ্তি"
  },
  ru: {
    "nav.tools": "Инструменты",
    "nav.pricing": "Цены",
    "nav.about": "О нас",
    "nav.contact": "Контакты",
    "nav.login": "Войти",
    "nav.signup": "Регистрация",
    "hero.title": "Платформа Онлайн-Инструментов Все-в-Одном",
    "hero.subtitle": "Загружайте видео, конвертируйте файлы, проверяйте скорость интернета и используйте 12+ мощных инструментов.",
    "hero.explore": "Изучить Инструменты",
    "hero.pricing": "Посмотреть Цены",
    "tools.popular": "Популярные Инструменты",
    "tools.subtitle": "Выберите из нашей коллекции мощных онлайн-инструментов",
    "tools.all": "Все Инструменты",
    "tools.video": "Видео Инструменты",
    "tools.converter": "Конвертеры",
    "tools.utility": "Утилиты",
    "tools.free": "Бесплатно",
    "tools.premium": "Премиум",
    "pricing.title": "Выберите Ваш План",
    "pricing.subtitle": "Разблокируйте премиум-функции и снимите ограничения",
    "pricing.free": "Бесплатно",
    "pricing.monthly": "Месячно",
    "pricing.yearly": "Годично",
    "pricing.current": "Текущий План",
    "pricing.getStarted": "Начать",
    "pricing.save": "Сэкономить 17%",
    "footer.tagline": "Ваше универсальное решение для всех онлайн-инструментов и утилит.",
    "footer.about": "О нас",
    "footer.contact": "Свяжитесь с нами",
    "footer.privacy": "Политика Конфиденциальности",
    "footer.terms": "Условия Сервиса",
    "footer.support": "Поддержка",
    "settings.title": "Настройки",
    "settings.account": "Настройки Аккаунта",
    "settings.language": "Язык",
    "settings.theme": "Тема",
    "settings.notifications": "Уведомления"
  },
  ar: {
    "nav.tools": "الأدوات",
    "nav.pricing": "الأسعار",
    "nav.about": "حول",
    "nav.contact": "اتصل",
    "nav.login": "تسجيل الدخول",
    "nav.signup": "إنشاء حساب",
    "hero.title": "منصة الأدوات المتكاملة عبر الإنترنت",
    "hero.subtitle": "تحميل الفيديوهات، تحويل الملفات، فحص سرعة الإنترنت، والوصول إلى 12+ أداة قوية.",
    "hero.explore": "استكشاف الأدوات",
    "hero.pricing": "عرض الأسعار",
    "tools.popular": "الأدوات الشائعة",
    "tools.subtitle": "اختر من مجموعة أدواتنا القوية عبر الإنترنت",
    "tools.all": "جميع الأدوات",
    "tools.video": "أدوات الفيديو",
    "tools.converter": "المحولات",
    "tools.utility": "الأدوات المساعدة",
    "tools.free": "مجاني",
    "tools.premium": "مميز",
    "pricing.title": "اختر خطتك",
    "pricing.subtitle": "فتح الميزات المميزة وإزالة القيود",
    "pricing.free": "مجاني",
    "pricing.monthly": "شهري",
    "pricing.yearly": "سنوي",
    "pricing.current": "الخطة الحالية",
    "pricing.getStarted": "ابدأ",
    "pricing.save": "وفر 17%",
    "footer.tagline": "حلك الشامل لجميع الأدوات والمرافق عبر الإنترنت.",
    "footer.about": "من نحن",
    "footer.contact": "اتصل بنا",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.support": "الدعم",
    "settings.title": "الإعدادات",
    "settings.account": "إعدادات الحساب",
    "settings.language": "اللغة",
    "settings.theme": "المظهر",
    "settings.notifications": "الإشعارات"
  },
  ja: {
    "nav.tools": "ツール",
    "nav.pricing": "価格",
    "nav.about": "について",
    "nav.contact": "お問い合わせ",
    "nav.login": "ログイン",
    "nav.signup": "サインアップ",
    "hero.title": "オールインワン オンラインツール プラットフォーム",
    "hero.subtitle": "動画をダウンロード、ファイル変換、インターネット速度チェック、12+のパワフルなツールにアクセス。",
    "hero.explore": "ツールを探索",
    "hero.pricing": "価格を見る",
    "tools.popular": "人気のツール",
    "tools.subtitle": "私たちの強力なオンラインツールのコレクションから選択",
    "tools.all": "すべてのツール",
    "tools.video": "ビデオツール",
    "tools.converter": "コンバーター",
    "tools.utility": "ユーティリティ",
    "tools.free": "無料",
    "tools.premium": "プレミアム",
    "pricing.title": "プランを選択",
    "pricing.subtitle": "プレミアム機能のロックを解除し、制限を削除",
    "pricing.free": "無料",
    "pricing.monthly": "月額",
    "pricing.yearly": "年額",
    "pricing.current": "現在のプラン",
    "pricing.getStarted": "始める",
    "pricing.save": "17%節約",
    "footer.tagline": "すべてのオンラインツールとユーティリティのワンストップソリューション。",
    "footer.about": "私たちについて",
    "footer.contact": "お問い合わせ",
    "footer.privacy": "プライバシーポリシー",
    "footer.terms": "利用規約",
    "footer.support": "サポート",
    "settings.title": "設定",
    "settings.account": "アカウント設定",
    "settings.language": "言語",
    "settings.theme": "テーマ",
    "settings.notifications": "通知"
  },
  ko: {
    "nav.tools": "도구",
    "nav.pricing": "가격",
    "nav.about": "소개",
    "nav.contact": "연락처",
    "nav.login": "로그인",
    "nav.signup": "가입",
    "hero.title": "올인원 온라인 도구 플랫폼",
    "hero.subtitle": "동영상 다운로드, 파일 변환, 인터넷 속도 확인, 12+ 강력한 도구에 액세스하세요.",
    "hero.explore": "도구 탐색",
    "hero.pricing": "가격 보기",
    "tools.popular": "인기 도구",
    "tools.subtitle": "강력한 온라인 도구 컬렉션에서 선택하세요",
    "tools.all": "모든 도구",
    "tools.video": "비디오 도구",
    "tools.converter": "변환기",
    "tools.utility": "유틸리티",
    "tools.free": "무료",
    "tools.premium": "프리미엄",
    "pricing.title": "플랜 선택",
    "pricing.subtitle": "프리미엄 기능 잠금 해제 및 제한 제거",
    "pricing.free": "무료",
    "pricing.monthly": "월간",
    "pricing.yearly": "연간",
    "pricing.current": "현재 플랜",
    "pricing.getStarted": "시작하기",
    "pricing.save": "17% 절약",
    "footer.tagline": "모든 온라인 도구와 유틸리티를 위한 원스톱 솔루션.",
    "footer.about": "회사 소개",
    "footer.contact": "문의하기",
    "footer.privacy": "개인정보 정책",
    "footer.terms": "서비스 약관",
    "footer.support": "지원",
    "settings.title": "설정",
    "settings.account": "계정 설정",
    "settings.language": "언어",
    "settings.theme": "테마",
    "settings.notifications": "알림"
  },
  fr: {
    "nav.tools": "Outils",
    "nav.pricing": "Prix",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "nav.login": "Se connecter",
    "nav.signup": "S'inscrire",
    "hero.title": "Plateforme d'Outils en Ligne Tout-en-Un",
    "hero.subtitle": "Téléchargez des vidéos, convertissez des fichiers, vérifiez la vitesse d'internet et accédez à 12+ outils puissants.",
    "hero.explore": "Explorer les Outils",
    "hero.pricing": "Voir les Prix",
    "tools.popular": "Outils Populaires",
    "tools.subtitle": "Choisissez parmi notre collection d'outils en ligne puissants",
    "tools.all": "Tous les Outils",
    "tools.video": "Outils Vidéo",
    "tools.converter": "Convertisseurs",
    "tools.utility": "Utilitaires",
    "tools.free": "Gratuit",
    "tools.premium": "Premium",
    "pricing.title": "Choisissez Votre Plan",
    "pricing.subtitle": "Débloquez les fonctionnalités premium et supprimez les limites",
    "pricing.free": "Gratuit",
    "pricing.monthly": "Mensuel",
    "pricing.yearly": "Annuel",
    "pricing.current": "Plan Actuel",
    "pricing.getStarted": "Commencer",
    "pricing.save": "Économisez 17%",
    "footer.tagline": "Votre solution complète pour tous les outils et utilitaires en ligne.",
    "footer.about": "À propos de nous",
    "footer.contact": "Contactez-nous",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions de Service",
    "footer.support": "Support",
    "settings.title": "Paramètres",
    "settings.account": "Paramètres de Compte",
    "settings.language": "Langue",
    "settings.theme": "Thème",
    "settings.notifications": "Notifications"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    try {
      const stored = localStorage.getItem('site_lang');
      return (stored as Language) || 'en';
    } catch (e) {
      return 'en';
    }
  });

  // Auto-detect browser language on first load if not set
  useEffect(() => {
  if (localStorage.getItem('site_lang')) return;
    try {
      const navLang = navigator.language || (navigator as any).userLanguage || 'en';
      const short = navLang.split('-')[0];
      const supported: Language[] = ['en','hi','zh','es','pt','bn','ru','ar','ja','ko','fr'];
      if (supported.includes(short as Language)) {
        setLanguage(short as Language);
        try { localStorage.setItem('site_lang', short); } catch (e) {}
      }
    } catch (e) {
      // ignore
    }
  }, []);

  // Persist language to cookie when changed
  useEffect(() => {
    try { localStorage.setItem('site_lang', language); } catch (e) {}
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
